apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongodb-depl      
spec:
  selector:
    matchLabels:
      app: mongodb 
  replicas: 4
  template:
    metadata:
      labels:
        app: mongodb 
    spec:
      containers:
      - name: mongodb 
        image: mongo:4.0.1 
        ports:
        - containerPort: 27017

